<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class MJadwal extends CI_Model
{

    public $table = 'jadwal';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    function get_semester()
    {
        return $this->db->get("semester")->row();
    }

    function get_jadwal($semester)
    {
        // $this->db->order_by('hari', 'ASC');
        $this->db->where('semester', $semester);
        return $this->db->get("v_jadwal")->result();
    }
    function get_jadwal_hari_ini($semester)
    {
        // $this->db->order_by('hari', 'ASC');
        $day_of_week = date('N', strtotime(date('D')));
        $this->db->where('semester', $semester);
        $this->db->where('hari', $day_of_week);
        $this->db->order_by('waktu_mulai', 'asc');
        return $this->db->get("v_jadwal")->result();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    function get_smt($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get('semester')->row();
    }

    // get total rows
    function total_rows($q = NULL)
    {
        $this->db->like('id', $q);
        $this->db->or_like('nama', $q);
        $this->db->or_like('waktu_mulai', $q);
        $this->db->or_like('waktu_akhir', $q);
        $this->db->or_like('hari', $q);
        $this->db->or_like('semester', $q);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL)
    {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
        $this->db->or_like('nama', $q);
        $this->db->or_like('waktu_mulai', $q);
        $this->db->or_like('waktu_akhir', $q);
        $this->db->or_like('hari', $q);
        $this->db->or_like('semester', $q);
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }
    function update_smt($data)
    {
        $this->db->update('semester', $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    // delete bulkdata
    function deletebulk()
    {
        $data = $this->input->post('msg_', TRUE);
        $arr_id = explode(",", $data);
        $this->db->where_in($this->id, $arr_id);
        return $this->db->delete($this->table);
    }
}

/* End of file MJadwal.php */
/* Location: ./application/models/MJadwal.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-05-27 16:54:05 */
/* http://harviacode.com */