<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Mv_ulangtahun extends CI_Model
{

    public $table = 'v_ulangtahun';
    public $id = 'id';
    public $order = 'ASC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        return $this->db->get($this->table)->result();
    }

    function get_next()
    {
        $this->db->limit(1);
        return $this->db->get($this->table)->row();
    }
}

/* End of file MMahasiswa.php */
/* Location: ./application/models/MMahasiswa.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-05-25 12:52:26 */
/* http://harviacode.com */